language: python
python:
    - "2.7"
cache:
    directories:
        - "~/.platformio"

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci --project-conf AVR/main/platformio.ini main