language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=./AVR/main
    - PLATFORMIO_CI_SRC=./AVR/main/main.ino

install:
    - pip install -U platformio
    - platformio lib -g install 44

script:
    - platformio ci --board=uno